#!/bin/bash

database=$1
user=$2
file=$database.`date +%Y-%m-%d`.sql.gz
count=0
while [[ -e $file ]] ; do
	count=$(( $count + 1 ))
	file=$database.`hostname`.`date +%Y-%m-%d`.$count.sql.gz
done

mysqldump -u $user -p "$database" | gzip > $file
