#!/bin/bash

database=$1
if [[ $# -lt 2 ]] ; then
	user=$USER
else
	user=$2
fi
file=$database.`hostname`.`date +%Y-%m-%d`.sql.gz
count=0
while [[ -e $file ]] ; do
	count=$(( $count + 1 ))
	file=$database.`hostname`.`date +%Y-%m-%d`.$count.sql.gz
done

mysqldump -u $user -p "$database" | gzip > $file
